#!/bin/bash
# Regenerate components/cinematic/{DesktopHome,MobileHome}.tsx and their CSS from the approved prototypes.
#   design/prototypes/desktop-universe.dc.html  →  DesktopHome.tsx + desktop.css   (scope .zhd)
#   design/prototypes/mobile.dc.html            →  MobileHome.tsx  + mobile.css    (scope .zhm)
# Production changes (real content, APIs, links, mobile window-scroll) live in prod.py.
# Usage: bash scripts/cinematic/gen.sh
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../.." && pwd)
M=$REPO/design/assets-manifest.json
P=$REPO/design/prototypes
OUT=$REPO/components/cinematic
TMP=$(mktemp -d)
python3 "$HERE/prod.py" "$P/desktop-universe.dc.html" "$TMP/desktop.dc.html" "$M" desktop
python3 "$HERE/prod.py" "$P/mobile.dc.html" "$TMP/mobile.dc.html" "$M" mobile
printf "import { PreBookModal, RankingsBlock, NewsletterBlock, ContactBlock } from './blocks'\nimport './desktop.css'\n" > "$TMP/imp_d.txt"
printf "import { PreBookModal, RankingsBlock, NewsletterBlock, ContactBlock, MobileMenu } from './blocks'\nimport './mobile.css'\n" > "$TMP/imp_m.txt"
python3 "$HERE/dc2tsx.py" "$TMP/desktop.dc.html" DesktopHome zhd "$OUT/DesktopHome.tsx" "$TMP/desktop.css" "$TMP/imp_d.txt"
python3 "$HERE/dc2tsx.py" "$TMP/mobile.dc.html" MobileHome zhm "$OUT/MobileHome.tsx" "$TMP/mobile.css" "$TMP/imp_m.txt"
BASE='/* reset Tailwind preflight inside the cinematic scope so the design renders exactly like the prototype */
SCOPE{line-height:normal;-webkit-text-size-adjust:100%}
SCOPE *,SCOPE *::before,SCOPE *::after{box-sizing:content-box}
SCOPE img,SCOPE video{max-width:none}
SCOPE button{font:inherit;color:inherit;line-height:normal}
SCOPE h1,SCOPE h2,SCOPE h3,SCOPE p,SCOPE figure{margin:0}
'
{ echo "/* AUTO-GENERATED by scripts/cinematic/gen.sh — desktop (Prototype B) */"; echo "${BASE//SCOPE/.zhd}"; cat "$TMP/desktop.css"; echo '@media (max-width:1240px){.zhd .navl{gap:20px}.zhd .navl a{font-size:12px;letter-spacing:.12em}}
@media (max-width:1060px){.zhd .navl a:nth-child(5),.zhd .navl a:nth-child(6){display:none}}'; } > "$OUT/desktop.css"
{ echo "/* AUTO-GENERATED by scripts/cinematic/gen.sh — mobile */"; echo "${BASE//SCOPE/.zhm}"; cat "$TMP/mobile.css"; echo '.zhm .zh-vh{height:100vh;height:100svh}
.zhm .nv{padding-top:env(safe-area-inset-top)}'; } > "$OUT/mobile.css"
rm -rf "$TMP"
echo "generated components/cinematic/{DesktopHome,MobileHome}.tsx"
